In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from __future__ import division

%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [3]:
pd.set_option('display.height', 1000)
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 100)
pd.set_option('display.width', 1000)

height has been deprecated.



In [4]:
cols = pd.read_csv('columns.csv', sep=';').columns
data = pd.read_csv('ds_interview_dataset.csv', sep = ';', header = None)
data.columns = list(cols)

In [5]:
data['Date of birth'] = pd.to_datetime(data['Date of birth'])
data['First purchase date'] = pd.to_datetime(data['First purchase date'])
data['Date of purchase'] = pd.to_datetime(data['Date of purchase'])
data['VIP'] = data['VIP'].map({'NO':0, 'YES':1})
data['Promo Sign'] = data['Promo Sign'].map({'N':0, 'Y':1})
data['Age'] = (data['Date of purchase']-data['Date of birth']).dt.days/365.25
data['Age'] = data['Age'].fillna(0).astype(int)

In [6]:
def age_group(x):
    if x < 14 or x > 69:
        return 'na'
    elif x>=14 and x<20:
        return '14-19'
    elif x>=20 and x<30:
        return '20-29'
    elif x>=30 and x<40:
        return '30-39'
    elif x>=40 and x<50:
        return '40-49'
    elif x>=50 and x <60:
        return '50-59'
    elif x>=60 and x<70:
        return '60-69'

In [7]:
data['Age_Group'] = data['Age'].map(age_group)

In [8]:
data['YEAR_fst_purchase'] = data['First purchase date'].dt.year
data['MONTH_fst_purchase'] = data['First purchase date'].dt.month
data['LT'] = (data['Date of purchase'].dt.year-data['YEAR_fst_purchase'])*12 - data['MONTH_fst_purchase'] + data['Date of purchase'].dt.month

In [9]:
data['refund'] = (data['Revenue']<0)*1
purchase = data[data.refund != 1] 
refund   = data[data.refund == 1]

In [10]:
year_agg_purchase = purchase.groupby('Customer ID')['Revenue'].agg({'sum', 'mean', 'count'})
year_agg_purchase.columns = ['purchases', 'revenue', 'aov']

year_agg_refund = refund.groupby('Customer ID')['Revenue'].agg({'sum', 'mean', 'count'})
year_agg_refund.columns = ['refunds', 'refund_revenue', 'aov_refund']

In [11]:
### promo pivots

In [12]:
year_agg_purchase_promo = purchase.groupby(['Customer ID', 'Promo Sign'])['Revenue'].agg({'sum', 'mean', 'count'})
year_agg_purchase_promo.columns = ['purchases', 'revenue', 'aov']

purchase_promo_pivot = year_agg_purchase_promo.unstack().fillna(0)
ind = pd.Index([str(e[0]) + "_" + 'promo_' + str(e[1])  for e in purchase_promo_pivot.columns.tolist()])
purchase_promo_pivot.columns = ind

year_agg_refund_promo = refund.groupby(['Customer ID', 'Promo Sign'])['Revenue'].agg({'sum', 'mean', 'count'})
year_agg_refund_promo.columns = ['refunds', 'refund_revenue', 'aov_refund']

refund_promo_pivot = year_agg_refund_promo.unstack().fillna(0)
ind = pd.Index([str(e[0]) + "_" + 'promo_' + str(e[1])  for e in refund_promo_pivot.columns.tolist()])
refund_promo_pivot.columns = ind

In [13]:
#### Channels pivot

In [14]:
year_agg_purchase_channel = purchase.groupby(['Customer ID', 'Sales Channel'])['Revenue'].agg({'sum', 'mean', 'count'})
year_agg_purchase_channel.columns = ['purchases', 'revenue', 'aov']

purchase_channel_pivot = year_agg_purchase_channel.unstack().fillna(0)
ind = pd.Index([str(e[0]) + "_"  + str(e[1])  for e in purchase_channel_pivot.columns.tolist()])
purchase_channel_pivot.columns = ind

year_agg_refund_channel = refund.groupby(['Customer ID', 'Sales Channel'])['Revenue'].agg({'sum', 'mean', 'count'})
year_agg_refund_channel.columns = ['refunds', 'refund_revenue', 'aov_refund']

refund_channel_pivot = year_agg_refund_channel.unstack().fillna(0)
ind = pd.Index([str(e[0]) + "_"  + str(e[1])  for e in refund_channel_pivot.columns.tolist()])
refund_channel_pivot.columns = ind

In [15]:
#### product group pivot

In [16]:
year_agg_purchase_group = purchase.groupby(['Customer ID', 'Product Group'])['Revenue'].agg({'sum', 'mean', 'count'})
year_agg_purchase_group.columns = ['purchases', 'revenue', 'aov']

purchase_group_pivot = year_agg_purchase_group.unstack().fillna(0)
ind = pd.Index([str(e[0]) + "_"  + str(e[1])  for e in purchase_group_pivot.columns.tolist()])
purchase_group_pivot.columns = ind

year_agg_refund_group = refund.groupby(['Customer ID', 'Product Group'])['Revenue'].agg({'sum', 'mean', 'count'})
year_agg_refund_group.columns = ['refunds', 'refund_revenue', 'aov_refund']

refund_group_pivot = year_agg_refund_group.unstack().fillna(0)
ind = pd.Index([str(e[0]) + "_"  + str(e[1])  for e in refund_group_pivot.columns.tolist()])
refund_group_pivot.columns = ind

In [17]:
### product gender

In [18]:
year_agg_purchase_gender = purchase.groupby(['Customer ID', 'Product Gender'])['Revenue'].agg({'sum', 'mean', 'count'})
year_agg_purchase_gender.columns = ['purchases', 'revenue', 'aov']

purchase_gender_pivot = year_agg_purchase_gender.unstack().fillna(0)
ind = pd.Index([str(e[0]) + "_"  + str(e[1])  for e in purchase_gender_pivot.columns.tolist()])
purchase_gender_pivot.columns = ind

year_agg_refund_gender = refund.groupby(['Customer ID', 'Product Gender'])['Revenue'].agg({'sum', 'mean', 'count'})
year_agg_refund_gender.columns = ['refunds', 'refund_revenue', 'aov_refund']

refund_gender_pivot = year_agg_refund_gender.unstack().fillna(0)
ind = pd.Index([str(e[0]) + "_"  + str(e[1])  for e in refund_gender_pivot.columns.tolist()])
refund_gender_pivot.columns = ind

In [19]:
### payment method pivot

In [20]:
year_agg_purchase_method = purchase.groupby(['Customer ID', 'Payment Method'])['Revenue'].agg({'sum', 'mean', 'count'})
year_agg_purchase_method.columns = ['purchases', 'revenue', 'aov']

purchase_method_pivot = year_agg_purchase_method.unstack().fillna(0)
ind = pd.Index([str(e[0]) + "_"  + str(e[1])  for e in purchase_method_pivot.columns.tolist()])
purchase_method_pivot.columns = ind

In [21]:
# purchase_method_pivot

In [22]:
f = {'Age_Group':['last'], 'LT':['max'], 'VIP':['max']}
clients = data.groupby(['Customer ID', 'Gender', 'Income Range']).agg(f)
clients.reset_index(level=['Gender', 'Income Range'], inplace=True)
clients.columns = clients.columns.droplevel(1)

In [23]:
clients_dummy = pd.get_dummies(clients)

In [24]:
def m(x,y):
    return pd.merge(x, y, left_index=True, right_index=True, how='left').fillna(0)

In [25]:
df = m(m(clients_dummy,year_agg_purchase),year_agg_refund)
df = m(m(df,purchase_promo_pivot),refund_promo_pivot)
df = m(m(df,purchase_channel_pivot),refund_channel_pivot)
df = m(m(df,purchase_group_pivot),refund_group_pivot)
df = m(m(df,purchase_gender_pivot),refund_gender_pivot)
df = m(df,purchase_method_pivot)

In [26]:
new_col = list(df.columns[:18]) + [x for x in df.columns if 'revenue' in x and 'refund' not in x]

In [27]:
df_new = df[new_col]

In [28]:
for col in [x for x in df.columns if 'revenue_' in x and 'refund' not in x]:
    df_new[col] = df_new[col] / df_new['revenue']

/Users/imanyakhin/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app


In [29]:
from sklearn import cluster

In [30]:
kMA = cluster.KMeans(n_clusters=5)
kMA.fit(df_new[(df_new.Gender_UNDEFINED==0) & (df_new.purchases<23)].fillna(0))

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=5, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [31]:
pd.DataFrame(kMA.cluster_centers_, columns = df_new.columns).to_csv('all_5.csv', sep = ';', decimal = ',')

In [32]:
np.unique(kMA.labels_, return_counts=True)

(array([0, 1, 2, 3, 4], dtype=int32),
 array([1321601,  615561,   59919,    9807,  212942]))

In [33]:
df_new = df_new[(df_new.Gender_UNDEFINED==0) & (df_new.purchases<23)]

In [34]:
df_new['segm'] = kMA.labels_

In [35]:
df_new = df_new[(df_new.segm==1)|(df_new.segm==2)|(df_new.segm==4)]

In [37]:
rev_col = [x for x in df_new.columns if 'revenue_' in x and 'refund' not in x]

In [38]:
rev_col = [x for x in rev_col if 'card' not in x and 'cash' not in x and 'gift' not in x]

In [39]:
kMR = cluster.KMeans(n_clusters=10)
kMR.fit(df_new[rev_col].fillna(0))

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=10, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [40]:
pd.DataFrame(kMR.cluster_centers_, columns = rev_col).to_csv('kmr.csv', sep = ';', decimal = ',')

In [41]:
np.unique(kMR.labels_, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32),
 array([131035,  30704, 104790,  67324, 161577, 160883,  51546,  74499,
         56733,  49331]))